### PR TITLE
fixed grammar in readme file

### PR DESCRIPTION
**Pull request by open-source-newbie**
Hi! Fixed a couple of minor grammar errors in your README file. Thanks for making this project!

### CODE REVIEW

**Comment by gremlin16** [comment]
thanks, I'll take a look at it <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by gremlin16** [comment]
thanks, I'll take a look at it

**Comment by gremlin16** [comment]
Thanks!

**Comment by gremlin16** [comment]
Thanks!

**Comment by gremlin16** [comment]
Thanks!

**Comment by gremlin16** [comment]
Thanks!

**Comment by gremlin16** [comment]
hello

**Comment by gremlin16** [comment]
Thanks!

**Comment by gremlin16** [comment]
Thanks!

**Comment by gremlin16** [comment]
hello again

**Comment by open-source-newbie** [comment]
test

**Pull request merged**
